---
kind: pipeline
type: kubernetes
name: Discover PaperMC releases
trigger:
  event: 
    exclude:
      - promote
steps:
  - name: Build
    image: golang:1.18.2-alpine
    commands:
      - go build -o bin/discover github.com/dockcenter/paper/cmd/discover
  - name: Discover releases
    image: alpine
    environment:
      DRONE_SERVER: http://drone
      DRONE_TOKEN:
        from_secret: drone_token
    commands:
      - apk --no-cache add curl tar
      - curl -L https://github.com/harness/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx
      - install -t /usr/local/bin drone
      - bin/discover
      - sh scripts/promote.sh

---
kind: pipeline
type: kubernetes
name: Publish
trigger:
  event:
    - promote
steps:
  - name: Build Docker image
    image: plugins/docker
    when:
      target:
        - development
    settings:
      dockerfile: Dockerfile
      dry_run: true
      repo: dockcenter/paper
      tags: ${DOCKER_TAGS}
      build_args_from_env:
        - DOWNLOAD_URL
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 1440
  - name: Publish Docker image
    image: plugins/docker
    when:
      target:
        exclude:
          - development
    settings:
      dockerfile: Dockerfile
      repo: dockcenter/paper
      tags: ${DOCKER_TAGS}
      build_args_from_env:
        - BASE_IMAGE_TAG
        - DOWNLOAD_URL
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 1440

---
kind: signature
hmac: 748d39b8c3350eb46ce41601d85a4d888610427584670aa8e333bd2fd1f2af47

...
